# Generated by Django 5.0.6 on 2024-06-21 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('Task', '0003_alter_task_taskdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='task',
        ),
        migrations.AddField(
            model_name='category',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Task.task'),
        ),
    ]
