# Generated by Django 5.0.6 on 2024-06-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=50)),
                ('taskDescription', models.CharField(max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('TaskAssignDate', models.DateTimeField()),
            ],
        ),
    ]
