# Generated by Django 5.0.6 on 2024-06-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='TaskAssignDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
