# Generated by Django 5.0.6 on 2024-06-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_alter_task_taskassigndate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskDescription',
            field=models.TextField(),
        ),
    ]
