# Generated by Django 5.0.6 on 2024-06-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_task_taskdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='TaskAssignDate',
            new_name='taskAssignDate',
        ),
        migrations.AlterField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(max_length=200),
        ),
    ]
